### ISSUE TITLE
LWM2M / CoAP

### ISSUE THREAD

**Issue by eeFLis** [u-blox/ubxlib#11]
Hello 
Are there plans for a LWM2M and Coap client?

**Comment by hkro** [comment]
Hi there, currently we have a couple of features scheduled for implementation. Find all the requested features [here](https://github.com/u-blox/ubxlib/issues?q=is%3Aopen+label%3Afeature+sort%3Areactions-%2B1-desc) for voting.

Following the number of up-votes we'll roll them out in upcoming releases. Current focus is on WiFi and GNSS API, thereafter we'll consider LwM2M/CoAP support depending on the demand.

**Comment by manemannen** [comment]
Project is discontinued

**Comment by manemannen** [comment]
Project is discontinued
