### ISSUE TITLE
Auto-Baud support for GNSS UART

### ISSUE THREAD

**Issue by bperseghetti** [u-blox/ubxlib#114]
Currently the implementation requires setting fixed baud rate, however, when reconfiguring/rebooting system the MCU and GNSS (F9P/M8N) can be out of sync of the uart baud rate. Having autoconfigure of baud rate in ubxlib would solve this issue.

Zephyr supports dynamically changing baud rate and having this in ubxlib is very important from a stability/user-experience perspective.

**Comment by RobMeades** [comment]
Hi there, and thanks for posting.  How would you see this working?  From what you've said, I guess we would allow a baud-rate setting of -1 for GNSS and, when we get that, we would send a UBX command at the standard baud rates 9600, 19200, 38400, 57600, 115200 until it is acknowledged, else we return an error?

**Comment by bperseghetti** [comment]
Something like this would be good:
https://github.com/PX4/PX4-GPSDrivers/blob/261480cb78a3ba60cdda2dcc95b874ebc2c9312c/src/ubx.cpp#L108-L236

Also an ideal case would be able to auto-detect a F9P/R/H/T vs M8N, M10, ... etc.

**Comment by bperseghetti** [comment]
@beriberikix you have any thoughts as well ^

**Comment by RobMeades** [comment]
Ah, yes, a more sensible ordering of baud rates there.  Doesn't look too difficult, we can put it on the list, though it might have to come after release 1.3 as that is occupying most time at the moment.  To be clear, that doesn't mean it has to be months away in release 1.4, we can push features out whenever.

On the auto-detecting module-type front, that has been on our list but I have been hesitant as it is quite difficult to test; we do not have all module variants in our `ubxlib` test farm and it would be easy to get one wrong if a name happens to be a bit "left of centre" in the ID reported-back by any of our modules.

However, we could implement something which we know works for the cases we _do_ know about, with enough flexibility that we think it should work in all cases, and add a caveat that, should anyone spot a hole in our implementation, they should report it and we will fix it.

**Comment by bperseghetti** [comment]
Ok, yeah, that would be good, as we are having issues with default initial bauds at 115200 but needed baud at 38400.

**Comment by bperseghetti** [comment]
We have F9P and M8N that we can test it on for you as well. Those are our highest priority ones.

**Comment by bperseghetti** [comment]
Circling back on this to see if this was ever added to any desired release road-map or not.

**Comment by RobMeades** [comment]
Yes, it is on the list for 1.4, due start of next year.  We need to post a list of things that will be in 1.4 here, will do that next week.

**Comment by bperseghetti** [comment]
Have you ever played with using milestones in github projects and attaching feature requests to them or bugs? https://github.com/u-blox/ubxlib/projects?query=is%3Aopen

**Comment by RobMeades** [comment]
Interesting: I'll mention it to our project manager.  Internally we use Jira for project management, the issue might be that we are clinging to a legacy [very cheap!] Github billing plan and most of this 'ere modern stuff isn't included in it, at least not on the private repo that we first push our PRs to.

**Comment by RobMeades** [comment]
This is now done in commit https://github.com/u-blox/ubxlib/commit/7c49f026c89a6e2c6b2269f16774de45d1ead543: supply 0 for the baud rate of a GNSS device connected via UART and the various rates will be tried until one that works is found.

I will close this now: please re-open, or start a new issue, if there is more to discuss.
