### ISSUE TITLE
No connection after firmware update

### ISSUE THREAD

**Issue by alexmaron81** [u-blox/ubxlib#122]
U_CELL: initialising with enable power pin not connected, PWR_ON pin 21 (0x15) (and is toggled from 1 to 0) and VInt pin not connected.
AT
AT
AT
AT
AT
U_CELL_PWR: powering on.
[00]AT
AT
AT
AT
AT
AT
AT
AT
AT
[00]AT
AT

OK
ATE0
ATE0

OK
AT+CMEE=2

OK
AT+UDCONF=1,0

OK
ATI9

M0.12.00,A.02.21

OK
AT&C1

OK
AT&D0

OK
AT+UCGED=5

OK
AT&K3

OK
AT+UPSV=4

OK
AT+CPSMS?

+CPSMS:0,,,"00011000","00001010"

OK
AT+CEDRXS?

+CEDRXS: 2,"0010"
+CEDRXS: 4,"0010"
+CEDRXS: 5,"0010"

OK
AT+CEDRXS=2,2

OK
AT+CEDRXS=2,4

OK
AT+CEDRXS=2,5

OK
AT+UMNOPROF?

+UMNOPROF: 0

OK
AT+UGPRF?

+UGPRF: 2,0,""

OK
AT+CFUN=4

OK
Opened device with return code 0.
Bringing up the network...
U_CELL_NET: preparing to register/connect...
AT+CREG=2

OK
AT+CGREG=2

OK
AT+CEREG=4

OK
AT+CIMI

901405103271762

OK
U_CELL_NET: user-specified APN is "iot.1nce.net".
AT+CGDCONT=1,"IP","iot.1nce.net"

OK
U_CELL_NET: setting automatic network selection mode...
AT+COPS?

+COPS: 0

OK
AT+CFUN=1

OK
AT+CREG?

+CREG: 2,0

OK
0: NReg
AT+CGREG?

+CGREG: 2,4

OK
0: OoC
AT+CEREG?

+CEREG: 4,0

OK
0: NReg
AT+CREG?

+CREG: 2,0

OK
0: NReg
AT+CGREG?

+CGREG: 2,4

OK
0: OoC
AT+CEREG?

+CEREG: 4,0

OK
0: NReg
AT+CREG?

+CREG: 2,0

OK
0: NReg
AT+CGREG?

+CGREG: 2,4

OK
0: OoC
AT+CEREG?

+CEREG: 4,0

OK
0: NReg
AT+CREG?

+CREG: 2,0

OK
0: NReg
AT+CGREG?

+CGREG: 2,4

OK
0: OoC
AT+CEREG?

+CEREG: 4,0

OK
0: NReg
AT+CREG?

+CREG: 2,0

OK
0: NReg
AT+CGREG?

+CGREG: 2,4

OK
0: OoC
AT+CEREG?

+CEREG: 4,0

OK
0: NReg
AT+CREG?

+CREG: 2,0

OK
0: NReg
AT+CGREG?

+CGREG: 2,4

OK
0: OoC
AT+CEREG?

+CEREG: 4,0

OK
0: NReg
AT+CREG?

+CREG: 2,0

OK
0: NReg
AT+CGREG?

+CGREG: 2,4

OK
0: OoC
AT+CEREG?

+CEREG: 4,0

OK
0: NReg
AT+CREG?

+CREG: 2,0

OK
0: NReg
AT+CGREG?

+CGREG: 2,4

OK
0: OoC
AT+CEREG?

+CEREG: 4,0

OK
0: NReg
AT+CREG?

+CREG: 2,0

OK
0: NReg
AT+CGREG?

+CGREG: 2,4

OK
0: OoC
AT+CEREG?

+CEREG: 4,0

OK
0: NReg
AT+CREG?

+CREG: 2,0

OK
0: NReg
AT+CGREG?

+CGREG: 2,4

OK
0: OoC
AT+CEREG?

+CEREG: 4,0

OK
0: NReg
AT+CREG?

+CREG: 2,0

OK
0: NReg
AT+CGREG?

+CGREG: 2,4

OK
0: OoC
AT+CEREG?

+CEREG: 4,0

OK
0: NReg
AT+CREG?

+CREG: 2,0

OK
0: NReg
AT+CGREG?

+CGREG: 2,4

OK
0: OoC
AT+CEREG?

+CEREG: 4,0

OK
0: NReg
AT+CREG?

+CREG: 2,0

**Comment by RobMeades** [comment]
Hi Alex.  Looking at #25, with the virtual network operator of your SIM (1nce) you ended up registered on the physical network of Deutsche Telecom and, I believe, on 2G.  If the RAT settings of the module happen to include NBIot, a complete network search can take 10s of minutes, so it might just take a while to get to 2G.  Forcing a manual selection on Deutsche Telecom likely cuts through that long process, 'cos you're telling the module exactly what you want.

That's my guess anyway.  All 3GPP stuff, not really something `ubxlib` knows much about I'm afraid.
