### ISSUE TITLE
Updating uPortUartInit() for Power Savings

### ISSUE THREAD

**Issue by TryingToGITthis** [u-blox/ubxlib#127]
On an nRF9160, we can save several mA by disabling the serial port with CONFIG_SERIAL. Please consider wrapping the the KERNEL_VERSION_MAJOR block with "#ifdef CONFIG_SERIAL" so an error isn't thrown when trying to compile.

**Comment by RobMeades** [comment]
Ah, so I guess `uart0` disappears if `CONFIG_SERIAL` is not defined?

**Comment by TryingToGITthis** [comment]
Correct.

For anyone else searching, this is the error you will get without the wrapper.

d:/ncs/toolchains/31f4403e35/opt/zephyr-sdk/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd.exe: app/libapp.a(u_port_uart.c.obj): in function `uPortUartInit':
D:\ncs\Code\ubxlib\port\platform\zephyr\src\u_port_uart.c:344: undefined reference to `__device_dts_ord_78'
d:/ncs/toolchains/31f4403e35/opt/zephyr-sdk/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd.exe: D:\ncs\Code\ubxlib\port\platform\zephyr\src\u_port_uart.c:344: undefined reference to `__device_dts_ord_80'

**Comment by TryingToGITthis** [comment]
That is exactly what I have and it works.

**Comment by RobMeades** [comment]
Perfect: testing has passed, will merge tomorrow after review.

**Comment by RobMeades** [comment]
Now available on `master` here at this commit:

https://github.com/u-blox/ubxlib/commit/97f7c89c6a4e633bc8405e01abb58c9e2501cd60

Will delete the preview branch and close this issue: please feel free to re-open it or open another if there are problems.
