### ISSUE TITLE
GNSS API

### ISSUE THREAD

**Issue by hkro** [u-blox/ubxlib#13]
Offer a very simple location API, providing a means to establish position using any u-blox module, potentially in conjunction with cloud services.

**Comment by ferremarco** [comment]
Support for SARA-R510M8S modules with integrated GNSS.

**Comment by hkro** [comment]
https://github.com/u-blox/ubxlib/issues/12#issuecomment-843264422

**Comment by hkro** [comment]
> Support for SARA-R510M8S modules with integrated GNSS.

It will also support SARA-R510M8S.
