### ISSUE TITLE
Error code 13,8 

### ISSUE THREAD

**Issue by michaelboeding** [u-blox/ubxlib#148]
https://portal.u-blox.com/s/question/0D52p0000CuRqftCQC/sara-510m8s-fails-to-reconnect-to-mqtt-broker-after-mno-switch 

I believe I'm running into the issue from the link above on my current device running 02.06,A00.01 . It only happens now and then but seems to be one of the reasons I've been running into intermediate MQTT disconnects on further investigation. I ran a test overnight that didn't drop once but while running the rest of the day its happened twice. 

```bash 

+UUMQTTC: 1,0
AT

OK
AT+UMQTTER

+UMQTTER: 13,8

OK
U_CELL_MQTT: error codes 13, 8.
AT+UMQTTER

+UMQTTER: 13,8

OK
AT+UMQTTER
Task is running

+UMQTTER: 13,8

OK
U_CELL_MQTT: error codes 13, 8.


```

My main question here is that it seems like the solution was to get an NDA signed and get a pre-released version of the firmware (from the link). Is this now publicly available? And should we implement a solution where we update the modules before production or is there a way to do this over an OTA firmware update that I either bundle with my main MCU firmware or separately. 

```txt
Hi gde,
 
I contacted uBlox about the issue and they advised i updated the module software to 2.09.
By default de modules came with version 2.06 and this contained some MQTT related bugs. They asked i sign an NDA for the (pre released software version of 2.09) and i updated the module via software tools (which they provided, with manual).
 
i haven't seen the problem since, but in should mention that i also added delays after losing connection before trying to reconnect to the MQTT side. So when the module sends the messages:
 
+CEREG: 0
+CEREG: 3,,,,0,9
+UUMQTTC: 0,101
 
i waited for about a minute before attempting a reconnect (the module should re-connect/switch to the new MNO within this time) to the MQTT broker, if this does not happen i re-try (rebuild) the connection and afterwards retry the MQTT connection.

```

**Comment by RobMeades** [comment]
Hi Michael: since I believe you have now moved to the PPP interface and the ESP-IDF native MQTT client I'm going to close this, feel free to re-open if there is more to discuss.
