### ISSUE TITLE
Module crashing after AT+CFUN=4?

### ISSUE THREAD

**Issue by arnoutdekimo** [u-blox/ubxlib#167]
Hi,

I've seen a few times now that after the module was unpowered, and I power it, and run ubxlib, that after it executes the CFUN=4 command, the module seems to crash?

[atcfun4reset.zip](https://github.com/u-blox/ubxlib/files/13391864/atcfun4reset.zip)
[consolelog.txt](https://github.com/u-blox/ubxlib/files/13391888/consolelog.txt)

I assume this is because somehow the uart RX line goes low for a long time.
Ubxlib then decides to toggle the pwron pin, but afterwards just keeps sending AT for a long time, before finally recovering

I'm guessing the root issue seems to be a crash of the module during AT+CFUN=4?

Kind regards,
Arnout

**Comment by RobMeades** [comment]
When you say "the module crashes", I guess you are referring to about here in your console log:

![image](https://github.com/u-blox/ubxlib/assets/6726745/e8def04f-f83e-4be4-8a9e-2876966adb3c)

If I've lined them up correctly, at the same point the Saleae log shows this:

![image](https://github.com/u-blox/ubxlib/assets/6726745/2fa97a1a-75f3-4fed-ac6d-9c5eae79fea7)

So it looks like the OK did come back, it just didn't arrive at `ubxlib` for some reason.  Have I misunderstood?

**Comment by RobMeades** [comment]
Ah, no I see the Saleae log starts later, hence what I'm seeing above is the second `AT+CFUN=4` not the first.

**Comment by RobMeades** [comment]
So, just to line us up, the repeated `AT`s, which is `ubxlib` trying to get a response back from the module, are here:

![image](https://github.com/u-blox/ubxlib/assets/6726745/483b1913-03d2-416f-a2fe-0219d9fa1bfd)

...where, as you say, the RX line goes low for some time.

**Comment by arnoutdekimo** [comment]
Ah..

The capture looks like this:

![image](https://github.com/u-blox/ubxlib/assets/61543845/1bf0656f-e63b-4d53-b19f-2dcd913ed944)
![image](https://github.com/u-blox/ubxlib/assets/61543845/116fb589-87f1-409d-9110-867381871f86)


The RX line only goes low a few seconds after the last AT command. It does not match your screenshot

**Comment by RobMeades** [comment]
Ah, yes, sorry, too many `.sal` files in too many places :-).

**Comment by RobMeades** [comment]
I wondered, from the timing, if it could be UART power saving but you have `AT+UPSV=0` so it can't be that.  If you are not doing so already it is probably worth monitoring VINT, which may go low momentarily if the module is truly reset.  These modules usually tend to spit something out on the RXD line when they restart, but there's no sign of that in this case.

I'm afraid for this one I would have to refer you to our usual module support route: where did you source our module from?

**Comment by arnoutdekimo** [comment]
Hi, 

I can indeed monitor the VINT pin.
I source the modules through the local distributor - batenburg. I can indeed get in contact with them directly as well regarding this issue

**Comment by RobMeades** [comment]
Please try that and, if you get nowhere, ping me via e-mail and I'll find a way.

**Comment by arnoutdekimo** [comment]
Presumably related to glitch on PWRON as well (https://github.com/u-blox/ubxlib/issues/163)

**Comment by RobMeades** [comment]
Hi Arnout: did you get any resolution to this through your local distributor?  If you think there is still stuff to discuss, you know where to find me, otherwise I will close this now (please re-open it if you wish).
