### ISSUE TITLE
support UART connection from PC application

### ISSUE THREAD

**Issue by sbans-ff** [u-blox/ubxlib#181]
I am trying to use this library to test my UBLOX GNSS device from a PC. I noticed that there does not seem to be a way to configure uDeviceCfg_t to interface with a ublox device using UART from a PC (i.e. you need to specify a tx and rx pin). Am I missing something or is it not supported?

**Comment by RobMeades** [comment]
Hi there: the pins are ignored when running on Windows, except that setting `pinCts` or `pinRts` to a non-negative value will enable flow control.  Just set the UART number to be whatever COM port number you are using.

**Comment by sbans-ff** [comment]
Will give that a shot. Thank you!
