### ISSUE TITLE
Truncation Warnings from snprintf

### ISSUE THREAD

**Issue by AarC10** [u-blox/ubxlib#190]
Currently a few files have truncation warnings with snprintf. I understand this problem would be resolved with using GCC 12.3 looking at the code, but this may not be possible for certain platforms. For example, Zephyr's SDK currently supports GCC 12.2 and using the cross-compiler option for arm-non-eabi-gcc 13.2 may not be a viable option if specific headers also need to be included

**Comment by RobMeades** [comment]
Thanks for the PR!
