### ISSUE TITLE
Unable Establish ST-LINK between STM32CubeIDE and u-blox C030-R510M8S 

### ISSUE THREAD

**Issue by gwchin14** [u-blox/ubxlib#20]
Hi, Rob,

I have completed the ubxlib build (issue: https://github.com/u-blox/ubxlib/issues/3), but unable to run it on C030-R510M8S application development board. I have installed the USB ST-Link driver (https://www.st.com/content/st_com/en/products/development-tools/software-development-tools/stm32-software-development-tools/stm32-utilities/stsw-link009.html) but did not help. I believe you have the same board, how did configure/install the ST-LINK? Please assists, thanks. 

I have provided multiple screenshots for your reference:
<img width="1514" alt="ST-LINK_Drivers" src="https://user-images.githubusercontent.com/69915989/117964919-cba2c900-b354-11eb-9ce5-1b66078658ce.png">
<img width="1514" alt="DeviceManager" src="https://user-images.githubusercontent.com/69915989/117964943-cfcee680-b354-11eb-9d22-b2f44f1b61ae.png">
<img width="1514" alt="ST-LINK_Cofiguration" src="https://user-images.githubusercontent.com/69915989/117964965-d4939a80-b354-11eb-9711-9802998633cd.png">
<img width="1514" alt="ST-LINK_NotDetected" src="https://user-images.githubusercontent.com/69915989/117964979-d8bfb800-b354-11eb-8709-f5bcb66e14bd.png">
<img width="1514" alt="ST-LINK_Upgrade" src="https://user-images.githubusercontent.com/69915989/117964990-db221200-b354-11eb-9fe8-dcbc7b288c4b.png">

Regards,
Chin

**Comment by RobMeades** [comment]
First thing to check is the jumper on the board: the jumper must be on the side nearest the module.

**Comment by RobMeades** [comment]
And which of the four USB ports are you connecting to?  You should connect with the USB port which is on the top side of the board, mounted horizontally (on the same side as the Ethernet connector).

**Comment by gwchin14** [comment]
![DSC_3981](https://user-images.githubusercontent.com/69915989/117974605-54733200-b360-11eb-9268-11002c959c61.JPG)

Hi, Rob,

Attached image shows how I connect the board, which I believe it is correct, based on your description.

**Comment by gwchin14** [comment]
<img width="1514" alt="GDB_Server" src="https://user-images.githubusercontent.com/69915989/117978845-e11fef00-b364-11eb-9eb1-01170811632f.png">
Now I am getting the error as shown in the above image.

**Comment by RobMeades** [comment]
The jumper position looks correct and I think that's the right USB port, though it's a bit difficult to tell from the picture.  You should not have to install anything other than the STM32Cube IDE which installs everything it needs.  @philwareublox went through this procedure earlier in the week with the same board.  I'm not sure I've ever seen an "ST-Link DLL error" unfortunately.

Let's go back to basics; when you plug the USB cable into the board and your PC does a mapped drive appear on your PC and a COM port also appear?

**Comment by gwchin14** [comment]
Let's go back to basics; when you plug the USB cable into the board and your PC, does a mapped drive appear on your PC and a COM port also appear?
Answer: There isn't any COM port which appears, this is why I think there is something wrong. If I use C030-R412M board, a "STMicroelectronics STLink Virtual COM Port" will appear, but not for the case when I plug in a C030-R510M8S to the USB port of my laptop. Instead of COM Port, the STM32 appears as a Universal Serial Bus devices with the name of "STM32 STLink":
<img width="1514" alt="DeviceManager" src="https://user-images.githubusercontent.com/69915989/117994635-44188280-b373-11eb-8f38-0e1d024863a7.png">

**Comment by RobMeades** [comment]
Does a mapped drive appear on your PC?

**Comment by gwchin14** [comment]
No

**Comment by RobMeades** [comment]
The board is recognised as ST-Link, so it is connected, but since it doesn't do any of the things that it is meant to do it might be that the ST-Link tool or whatever has installed an entirely different image on the debug chip of the C030 board itself.  You need to somehow get it back to normal.  Next thing you're going to ask me is "how...?" but I've very little idea as I've never done this myself and my board is not in the same state as yours so I can't try anything out for you.  Let me think...

**Comment by RobMeades** [comment]
How about this:

- uninstall the thing you installed above with the link ending `stsw-link009.html`,
- install instead this tool:  [https://www.st.com/en/development-tools/stsw-link004.html](https://www.st.com/en/development-tools/stsw-link004.html),
- run it with the board plugged in and see if it offers to update the debug image on the board.

**Comment by gwchin14** [comment]
No luck after installing stsw-link004, ST-LINK DLL Error still occurs. How about make a factory reset on STM32 using hardware button? Is this possible?
<img width="1514" alt="ST-LINK_DLL_Error" src="https://user-images.githubusercontent.com/69915989/118143039-80b0b080-b43d-11eb-952b-6adfdd361f47.png">

**Comment by RobMeades** [comment]
It is the debug chip (STM32F103CBT6) that you need to reset somehow.  On the C027 boards there used to be pads to do this but I can't find equivalent pads on the C030 board.  I will ask internally how to do it but won't get an answer until next week now as it is public holidays in most of Europe.

**Comment by RobMeades** [comment]
I believe this has been resolved now (it was a matter of finding the right stuff to load onto the debug MCU in the right way), closing.
