### ISSUE TITLE
The gnss library for all current receivers (gen 9, gen 8) is sorely needed. Any ETA?

### ISSUE THREAD

**Issue by axelriet** [u-blox/ubxlib#21]

**Comment by hkro** [comment]
You can find Windows drivers for current receivers on each product website under 'Documentation & resources'. Like on these links for example.

https://www.u-blox.com/en/product/zed-f9p-module#tab-documentation-resources
https://www.u-blox.com/en/product/neo-m8-series#tab-documentation-resources

The GNSS API for ubxlib https://github.com/u-blox/ubxlib/issues/13 will be released in the next months.
