### ISSUE TITLE
no network service

### ISSUE THREAD

**Issue by alexmaron81** [u-blox/ubxlib#28]
Hi everyone.
I recently got "no network service" during registration.
![No network](https://user-images.githubusercontent.com/83282470/132466708-81b00f66-6e63-4e85-8b86-d4d9cd6f7c01.JPG)

**Comment by RobMeades** [comment]
Hi Alex: for general support issues concerning network registration, etc. (i.e. I can't see how this is related to `ubxlib`)  I'm afraid I will have to point you at the usual u-blox support mechanism, which would be to a) conduct your usual sensible debugging (what have I don't differently this time, is the SIM/antenna/environment the same, etc.) and then b) to contact the place you purchased the module from, describing the problem, what you have debugged about it, and include your module IMEI/SW version number (`ubxlib` spits this out in the AT log at every startup, the response to `ATI9`).

Unless there's a reason why you think this might be `ubxlib` related?
