### ISSUE TITLE
wrong ICCID

### ISSUE THREAD

**Issue by alexmaron81** [u-blox/ubxlib#48]
Hi, everyone,

I am trying to query the ICCID with the "uCellInfoGetIccidStr" function. But I get one character at the end of the number too many. what could be the problem?
bytesRead = uCellInfoGetIccidStr(networkHandle, ICCID_buffer, sizeof(ICCID_buffer));

here is the representation of the portal of my provider
![image](https://user-images.githubusercontent.com/83282470/166885613-84328320-180a-4f90-afae-e636a18e8f3d.png)

and here what the modem outputs
![image](https://user-images.githubusercontent.com/83282470/166886580-b92b9184-0351-4fbf-90f3-4d03e014f5b0.png)

**Comment by RobMeades** [comment]
Hi Alex: looks like you may have a case of this:

https://www.netmorem2m.com/iot-wiki/iccid-explained/#:~:text=NN%20C(X)-,An%20ICCID%20typically%20consists%20of%2019%20to%2020%20characters.,13%20digits%20will%20be%20visible.

**Comment by alexmaron81** [comment]
only the 19 characters are on the card.
OK that explains everything.
Will cut off the last character for me ;-)
