### ISSUE TITLE
Unable to bring up the network!

### ISSUE THREAD

**Issue by alexmaron81** [u-blox/ubxlib#51]
Hi,

sometimes the connection is not successfully established, so that the module no longer works.

Unfortunately I don't use the following options:
U_CFG_APP_PIN_CELL_ENABLE_POWER
U_CFG_APP_PIN_CELL_RESET
U_CFG_APP_PIN_CELL_VINT

What other option is there to reset the module via software?

**Comment by RobMeades** [comment]
Hi Alex: it would depend on the nature of the "no longer works".

If the module is responsive to AT commands then you can call `uCellPwrReboot()` and `ubxlib` will tell the module to reboot via the AT interface.

However, if the module is not responding to AT commands, the only way out that I am aware of would be a physical connection to either the `PWR_ON` or `RESET_N` pins of the module from one of your MCU pins; this could be done using any GPIO that you control of course.  You should check the [SARA-R4 System Integration Manual](https://www.u-blox.com/en/docs/UBX-16029218) for details of exactly what you need to do with those pins to effect a reset.

**Comment by alexmaron81** [comment]
ok nice, thanks for the info!

**Comment by alexmaron81** [comment]
Hi Rob, 

to use uCellPwrReboot() do I need u_cell_pwr.h? but then comes the following

![image](https://user-images.githubusercontent.com/83282470/174606353-d36ef64b-0790-4975-a5d5-b9340f94953d.png)

**Comment by RobMeades** [comment]
Hi Alex: yes, you'll need to #include `u_cell_net.h` just before `u_cell_pwr.h`.  We've removed this problem in the 1.0.0 release that we are about to make by just dumping all required headers into one `ubxlib.h` that you can include.

**Comment by alexmaron81** [comment]
Hi Rob, I run the uCellPwrReboot(devHandle, NULL); , but the device still does not turn on

![image](https://user-images.githubusercontent.com/83282470/183607497-ade55fe5-92f4-4228-93b4-6fd3a049e00b.png)

**Comment by RobMeades** [comment]
Can't remember whether we resolved this one or not now, maybe in direct comms?  Gonna close it - please re-open if there is still an issue.
