### ISSUE TITLE
SARA-R510S-01B NB1 support

### ISSUE THREAD

**Issue by eeFLis** [u-blox/ubxlib#52]
Hi

Shouldn't U_CELL_NET_RAT_NB1 be added to the SARA_R5 RATs since the 01B version supports it?
Or a new module type for the SARA-R510S-01B version?

regards

**Comment by RobMeades** [comment]
Hi there: yes, you're right, this is on the TODO list, was trying to figure out the right way to do it in order to avoid duplication.  Will move it further up the priority list but to get you working you can change [u_cell_private.c](https://github.com/u-blox/ubxlib/blob/master/cell/src/u_cell_private.c#L164):

```
        U_CELL_MODULE_TYPE_SARA_R5, 1500 /* Pwr On pull ms */, 2000 /* Pwr off pull ms */,
        6 /* Boot wait */, 10 /* Min awake */, 20 /* Pwr down wait */, 15 /* Reboot wait */, 10 /* AT timeout */,
        20 /* Cmd wait ms */, 3000 /* Resp max wait ms */, 4 /* radioOffCfun */, 150 /* resetHoldMilliseconds */,
        1 /* Simultaneous RATs */,
        (1UL << (int32_t) U_CELL_NET_RAT_CATM1) /* RATs */,
        ...
```

...to this:

```
        U_CELL_MODULE_TYPE_SARA_R5, 1500 /* Pwr On pull ms */, 2000 /* Pwr off pull ms */,
        6 /* Boot wait */, 10 /* Min awake */, 20 /* Pwr down wait */, 15 /* Reboot wait */, 10 /* AT timeout */,
        20 /* Cmd wait ms */, 3000 /* Resp max wait ms */, 4 /* radioOffCfun */, 150 /* resetHoldMilliseconds */,
        2 /* Simultaneous RATs */,
        ((1UL << (int32_t) U_CELL_NET_RAT_CATM1) | (1UL << (int32_t) U_CELL_NET_RAT_NB1)) /* RATs */,
        ...
```

**Comment by RobMeades** [comment]
We've now fixed this properly on the `master` branch in commit 1843f8b807affac056a70776b351b35c5a87e03c, hence closing this: please re-open if you still have a problem with this.
