### ISSUE TITLE
How do I get a correct DBM value?

### ISSUE THREAD

**Issue by alexmaron81** [u-blox/ubxlib#61]
I need the correct dbm value.

is it the right source?
https://github.com/u-blox/ubxlib/blob/75ab57e92bcf485bd16b8556c3b11a5f9c462bfe/cell/test/u_cell_info_test.c

**Comment by RobMeades** [comment]
Hi Alex: correct dBm value of what thing?  You have a choice of [uCellInfoGetRssiDbm()](https://github.com/u-blox/ubxlib/blob/master/cell/api/u_cell_info.h#L81) or [uCellInfoGetRsrpDbm()](https://github.com/u-blox/ubxlib/blob/master/cell/api/u_cell_info.h#L93).  I believe you are on NB1 so you _probably_ want RSRP.  Don't forget to call [uCellInfoRefreshRadioParameters()](https://github.com/u-blox/ubxlib/blob/master/cell/api/u_cell_info.h#L69) first!

**Comment by alexmaron81** [comment]
what's the difference between Rssi and Rsrp?

**Comment by RobMeades** [comment]
RSSI is the total received strength in the received bandwidth, RSRP is the total received strength of the wanted signal in a received bandwidth.  So RSSI will include things other than the specific serving signal.

This article seems quite informative: https://www.cablefree.net/wirelesstechnology/4glte/rsrp-rsrq-measurement-lte.

**Comment by alexmaron81** [comment]
but before that I have to build a connection "uNetworkInterfaceUp"?

**Comment by alexmaron81** [comment]
ok that works already

![image](https://user-images.githubusercontent.com/83282470/183368148-1496016d-b0a7-4414-80eb-0b303f4274a3.png)

Thanks for the help Rob!

**Comment by RobMeades** [comment]
Excellent!

**Comment by RobMeades** [comment]
...though it looks like you have a lot of interferers there (with RSSI being considerably higher than RSRP), and RSRP is pretty close to the lowest limit.  Good to know it though.

**Comment by alexmaron81** [comment]
Hi Rob,

Since I've been using the new version of the library, the RSSI value is 0.
Do you know what it could have to do with?
![image](https://user-images.githubusercontent.com/83282470/211730292-40e1103b-5b02-4ae3-958c-75f9324464fd.png)

**Comment by alexmaron81** [comment]
hello, sometimes the rssi value is zero.
What can be the reason?
![image](https://user-images.githubusercontent.com/83282470/214771209-c80b03fc-00da-4460-a310-293ac27a41a6.png)

**Comment by RobMeades** [comment]
Hi Alex: RSSI is zero because it is derived from the CSQ value and that sometimes just takes a while to update.  I notice that this is shortly after connection, you might just have to wait for a little while.

Frankly, though, RSSI is pretty meaningless for LTE: OK, there's a measured signal in the band but who knows what it is, it could be anything.  The thing that matters is RSRP: the level of the _wanted_ signal, and RSRQ: the level of the wanted signal relative to the noise.  You can see above that the level of the wanted signal is quite low but probably bearable at -112 dBm and RSRQ is -10 dB, so the module is actually pulling the wanted signal out of the noise.

**Comment by RobMeades** [comment]
Closing this one: please re-open if necessary.

**Comment by alexmaron81** [comment]
how can i find out, before a connection has been established, whether it will be possible to establish a connection at all?

My application is battery operated. So far it works quite well when the device is in good network coverage.
Some devices are not in a good position and try to establish a connection too often, so that the battery runs out quickly.

However, I can only query RSRQ once the connection has been established.

Is there a way to check the network quality beforehand?

**Comment by philwareublox** [comment]
Hi, 

Unfortunately LTE does not work like that and to get the 3GPP RSRQ/RSRP values you must be connected. 

Phil.
