### ISSUE TITLE
ubxlib support for Assist Now On-line, off-line and auto

### ISSUE THREAD

**Issue by owain-incus** [u-blox/ubxlib#63]
Is support for the various Assist now u-blox services planned. Sara R4 / R5 support these; but I don't think ubxlib does (yet).
If I want to use these services now must I just rely on the AT client functionality of the library and implement my own location service based on the Sara R4/R5 location services app note?

**Comment by RobMeades** [comment]
Hi Owain - I have to admit that the range of these services confuses me also, gimme a moment to consult...

**Comment by bbyers-UBCO** [comment]
@RobMeades I'm also curious about this, any update here?

**Comment by RobMeades** [comment]
Apologies, entirely forgot about this, have assigned it to myself and made a note to actually do something, though likely not until January now as I will need to find the right person internally.

**Comment by RobMeades** [comment]
Configuration of AssistNow is now supported, see https://github.com/u-blox/ubxlib/releases/tag/v1.3.0.

Closing this issue: if you have problems, please open another.
