### ISSUE TITLE
Cellular: Add some helper functions to set the bands to scan. 

### ISSUE THREAD

**Issue by philwareublox** [u-blox/ubxlib#8]
Setting the bands to scan on for cellular modules can be a pain, what with the 2^<band-1> nonsense....
Having a simple API for this would make it easy for customers.

Something like celEnableBands(x) and celDisableBands(y), with parameters that can extend, like celEnableBands(x, y, z, a, b, c);

Probably need a celClearBands() function to, to start fresh.
Topic for discussion.

**Comment by RobMeades** [comment]
Great idea Phil!

**Comment by RobMeades** [comment]
Done in commit https://github.com/u-blox/ubxlib/commit/69fe155a1b8fd96c0b3e0b021fd201911785db22.
