### ISSUE TITLE
socket get pending bytes

### ISSUE THREAD

**Issue by eeFLis** [u-blox/ubxlib#83]
Hi

Is there a way to read the socket pending bytes?
I have seen that this information is used internally in the UUSORD UUSORF URC, but is not available through the api.
The advantage over polling uCellSockRead() is that the uart can switch to sleep mode.

**Comment by RobMeades** [comment]
Hi there: you really are trying to squeeze every Joule of power out of the system!

There's no API for that at the moment but it would be easy enough to add.  Just to be clear on the use-case, if I've understood correctly you would like to be able to do `AT+USORD=0`, and we'd probably also support `AT+USORF=0`, and get back the number, API probably named something like `uCellSockPending()` (and it would decide which one to do based on whether the socket is TCP or UDP)?

Is that correct?

**Comment by RobMeades** [comment]
Or is it that you'd just like to retrieve the number that `ubxlib` has stored?

**Comment by RobMeades** [comment]
Got it, testing change now, hopefully will push it here tomorrow.

**Comment by RobMeades** [comment]
Hopefully resolved by b0007e3f83b8545432762067c8ea04c251dd63ac: please re-open this issue if not.

**Comment by eeFLis** [comment]
Great thanks.
