### ISSUE TITLE
Reading MQTT messages will return U_ERROR_COMMON_DEVICE_ERROR if there are no messages to read

### ISSUE THREAD

**Issue by philwareublox** [u-blox/ubxlib#85]
At least for cellular mqttReadMessages(), if there are no messages to read back, the function will return U_ERROR_COMMON_DEVICE_ERROR. 

Can I suggest if the AT command was successful, but no message, it can return and error, but something like U_ERROR_MQTT_NO_MESSAGES

The calling code then knows there are no more messages to read.

**Comment by RobMeades** [comment]
This should be resolved by commit bafe4e736a14771ee4279a4e9b6517c694268846.
